global:
  scrape_interval: 15s # intervalle de scrap des métriques

scrape_configs:
  # Scraper Node Exporter
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
